apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: projetofiap-identificacao-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: projetofiap-identificacao-deployment
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
