name: "Docker Image Build Test"

on:
  workflow_dispatch:
  pull_request:

jobs:

  build-image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Maven and JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Folder content debug
      run: ls -l

    - name: Run basic tests
      run: mvn test

    - name: Runs the database and application
      run: |
        docker build . -t projeto-fiap-identificacao
        cd ./src/test/resources/deploy
        ls -l
        sed -i 's/DB_PASSWORD_PLACEHOLDER/${{ secrets.PROJETOFIAP_DB_PASSWORD }}/g' docker-compose.yml
        docker-compose up -d

    - name: Wait for Container to be Live and Monitor Containers
      run: |
        timeout=300
        elapsed=0
        echo "Waiting for container to be live..."
        db_container_id=$(docker ps --filter name=db -q)
        app_container_id=$(docker ps --filter name=projeto-fiap-identificacao -q)
        
        while ! curl --output /dev/null --silent --head --fail http://localhost:80/liveness; do
          if [ $elapsed -ge $timeout ]; then
            echo "Timed out waiting for container to be live."
            echo "======================================================"
            echo "Database Logs:"
            docker logs $db_container_id --tail 50
            echo "======================================================"
            echo "Application Logs:"
            docker logs $app_container_id --tail 50
            echo "======================================================"
            exit 1
          fi
          printf '.'
        
          # Print the current status of Docker containers
          echo "======================================================"
          echo "Current time: $(date)"
          docker ps
          echo "======================================================"
          echo "Database Logs:"
          docker logs $db_container_id --tail 50
          echo "======================================================"
          echo "Application Logs:"
          docker logs $app_container_id --tail 50
          echo "======================================================"
        
          sleep 10
          elapsed=$((elapsed + 10))
        done
        echo "Container is live!"

    - name: Run BDD tests
      run: mvn -B verify -P bdd sonar:sonar -Dsonar.projectKey=${{ secrets.AWS_ACCESS_KEY_ID }} -Dsonar.jacoco.reportPaths=target/site/jacoco/jacoco.xml

    - name: Check for BDD tests failures
      run: |
        if grep -q '<error message=' target/surefire-reports/*.xml; then
          echo "Falha nos testes BDD"
          exit 1
        fi
