name: "Docker Image Build Test"

on:
  workflow_dispatch:
  pull_request:

jobs:

  build-image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Setup Maven and JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Run basic tests
      run: mvn test

    - name: Run BDD tests
      run: mvn -B verify -P bdd sonar:sonar -Dsonar.projectKey=${{ secrets.AWS_ACCESS_KEY_ID }} -Dsonar.jacoco.reportPaths=target/site/jacoco/jacoco.xml

    - name: Check for BDD tests failures
      run: |
        if grep -q '<error message=' target/surefire-reports/*.xml; then
          echo "Falha nos testes BDD"
          exit 1
        fi
    
    # Maven build
    - name: Build with Maven
      run: mvn package

   # Build Docker image
    - name: Build Docker image
      run: docker build .
